from __future__ import annotations

import shutil
from pathlib import Path


OUTPUT_MARKER = ".rayport-output"


class OutputPathError(ValueError):
    """Raised when an output path could delete or package source files."""


def validate_output_path(game_dir: str | Path, output_dir: str | Path) -> tuple[Path, Path]:
    game_path = Path(game_dir).resolve()
    output_path = Path(output_dir).resolve()

    if output_path == game_path:
        raise OutputPathError("Output directory cannot be the game directory")
    if game_path.is_relative_to(output_path):
        raise OutputPathError("Output directory cannot contain the game directory")
    return game_path, output_path


def output_ignore_paths(game_dir: str | Path, output_dir: str | Path) -> tuple[Path, ...]:
    game_path, output_path = validate_output_path(game_dir, output_dir)
    if output_path.is_relative_to(game_path):
        return (output_path,)
    return ()


def prepare_output_dir(game_dir: str | Path, output_dir: str | Path, force: bool = False) -> Path:
    _, output_path = validate_output_path(game_dir, output_dir)

    if output_path.exists() and not output_path.is_dir():
        raise OutputPathError(f"Output path is not a directory: {output_path}")

    if output_path.exists():
        entries = list(output_path.iterdir())
        marker = output_path / OUTPUT_MARKER
        if entries and not marker.is_file() and not force:
            raise OutputPathError(
                f"Refusing to delete non-Rayport directory: {output_path}\n"
                "Choose an empty directory or pass --force-output explicitly."
            )
        shutil.rmtree(output_path)

    output_path.mkdir(parents=True)
    (output_path / OUTPUT_MARKER).write_text("Generated by Rayport.\n", encoding="utf-8")
    return output_path
